# Generated by Django 5.2.8 on 2025-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('jti', models.CharField(max_length=500)),
                ('blacklisted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
