# Generated by Django 5.2.8 on 2025-12-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('public_id', models.CharField(max_length=500)),
                ('resource_type', models.CharField(max_length=100)),
                ('bytes', models.IntegerField()),
                ('secure_url', models.URLField()),
                ('display_name', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='a_books.book')),
            ],
        ),
    ]
