# Generated by Django 5.2.8 on 2025-12-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_books', '0002_bookmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmedia',
            name='file_name',
        ),
    ]
