# Generated by Django 5.2.8 on 2025-11-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_comments', '0002_alter_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='reply_to',
        ),
    ]
