### Sign-Up
POST http://127.0.0.1:8000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "first_name" : "tatsuki",
    "last_name" : "fujimoto",
    "email" : "fujimoto@gmail.com",
    "username" : "fujimoto",
    "password" : "t_password"
}

### Sign-Up Admin
POST http://127.0.0.1:8000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "first_name" : "admin",
    "last_name" : "admin",
    "email" : "empadmin@gmail.com",
    "username" : "empadmin",
    "is_admin" : "true",
    "password" : "admin121"
}