### Update Book
PATCH  http://127.0.0.1:8000/api/books/19/ HTTP/1.1
Content-Type: application/json

{
    "title" : "Hello Python!",
    "description" : "Learn Python from Zero "
}

                ### Update categories in Book ###
### Add new categories
PATCH  http://127.0.0.1:8000/api/books/22/categories/ HTTP/1.1
Content-Type: application/json

{
    "categories" : [30]
}

### Remove categories
DELETE  http://127.0.0.1:8000/api/books/18/categories/ HTTP/1.1
Content-Type: application/json

{
    "categories" : [29]
}

                ### Update authors in Book ###
### Add new authors
PATCH  http://127.0.0.1:8000/api/books/22/authors/ HTTP/1.1
Content-Type: application/json

{
    "authors" : [1]
}

### Remove authors
DELETE  http://127.0.0.1:8000/api/books/22/authors/ HTTP/1.1
Content-Type: application/json

{
    "authors" : [1]
}